---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
  - name: centos-7.3

suites:
  - name: default
    run_list:
      - recipe[vault_chef::install]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
      vault:
        version: '0.8.1'
        zip_file: 'vault_0.8.1_linux_amd64.zip'
        download_url: 'https://releases.hashicorp.com/vault/0.8.1/vault_0.8.1_linux_amd64.zip'

  - name: vault-cluster-01
    run_list:
      - recipe[vault_chef::install]
      - recipe[consul_chef::install]
    driver:
      network:
        - ['private_network', {ip: '10.0.10.10'}]
      customize:
        memory: 2048
        cpus: 1
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
      vault:
        version: '0.8.1'
        zip_file: 'vault_0.8.1_linux_amd64.zip'
        download_url: 'https://releases.hashicorp.com/vault/0.8.1/vault_0.8.1_linux_amd64.zip'
      consul:
        version: '0.9.2'
        zip_file: 'consul_0.9.2_linux_amd64.zip'
        download_url: 'https://releases.hashicorp.com/consul/0.9.2/consul_0.9.2_linux_amd64.zip'
        cluster_size: '3'
        bind_addr: '10.0.10.10'
        join_ip: '10.0.10.10'

  - name: vault-cluster-02
    run_list:
      - recipe[vault_chef::install]
      - recipe[consul_chef::install]
    driver:
      network:
        - ['private_network', {ip: '10.0.10.11'}]
      customize:
        memory: 2048
        cpus: 1
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
      vault:
        version: '0.8.1'
        zip_file: 'vault_0.8.1_linux_amd64.zip'
        download_url: 'https://releases.hashicorp.com/vault/0.8.1/vault_0.8.1_linux_amd64.zip'
      consul:
        version: '0.9.2'
        zip_file: 'consul_0.9.2_linux_amd64.zip'
        download_url: 'https://releases.hashicorp.com/consul/0.9.2/consul_0.9.2_linux_amd64.zip'
        cluster_size: '3'
        bind_addr: '10.0.10.11'
        join_ip: '10.0.10.10'

  - name: vault-cluster-03
    run_list:
      - recipe[vault_chef::install]
      - recipe[consul_chef::install]
    driver:
      network:
        - ['private_network', {ip: '10.0.10.12'}]
      customize:
        memory: 2048
        cpus: 1
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
      vault:
        version: '0.8.1'
        zip_file: 'vault_0.8.1_linux_amd64.zip'
        download_url: 'https://releases.hashicorp.com/vault/0.8.1/vault_0.8.1_linux_amd64.zip'
      consul:
        version: '0.9.2'
        zip_file: 'consul_0.9.2_linux_amd64.zip'
        download_url: 'https://releases.hashicorp.com/consul/0.9.2/consul_0.9.2_linux_amd64.zip'
        cluster_size: '3'
        bind_addr: '10.0.10.12'
        join_ip: '10.0.10.10'
